version: "3.9"
services:
  zookeeper:
      image: confluentinc/cp-zookeeper:latest
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - 22181:2181 

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # api:
  #   build: .
  #   deploy:
  #     mode: replicated
  #     replicas: 2
  #   ports:
  #     - "3015-3016:3005"
  #     - "50061-50062:50051"

  # nginx:
  #   image: nginx
  #   volumes:
  #   - ./configs/templates/nginx:/etc/nginx/templates
  #   ports:
  #   - "100010:80"
  #   environment:
  #   - HOST_API=${HOST_API}
  #   depends_on:
  #     - api

  # nginxGRPC:
  #   image: nginx
  #   volumes:
  #     - ./configs/templates/nginxGRPC:/etc/nginx/templates
  #     - ./configs/tls:/etc/nginx/certs
  #   ports:
  #     - "10011:1443"
  #   environment:
  #     - HOST_API=${HOST_API}
  #   depends_on:
  #     - api

networks:
  default:
    name: indefinite-studies-subscriptions-service-network